package constants

const (
	Success           = "success"
	DefaltCreatedBy   = "00000"
	DefaltUpdatedBy   = "00000"
	NAME              = "name"
	DESCRIPTION       = "description"
	PARENT_ORG_ID     = "parent_org_id"
	CTX_TENANTID      = "tenantID"
	TENANT_ID         = "tenantId"
	ROLE              = "role"
	TENANT            = "tenant"
	USER              = "user"
	RESOURCE_INSTANCE = "resource_instance"
	USER_TYPE         = "User"
	GROUP_TYPE        = "Group"

	RESOURCE_TYPE_CLIENT_ORG  = "ClientOrganizationUnit"
	RESOURCE_TYPE_BINDING     = "Binding"
	KEY                       = "key"
	ATTRIBUTES                = "attributes"
	PERMIT_RESOURCE_INSTANCES = "resource_instances"
	GIN_CONTEXT_KEY           = "GinContextKey"
	RESOURCE                  = "resource"
	ROW_STATUS                = "rowStatus"
	CREATED_AT                = "created_at"
	UPDATED_AT                = "updated_at"
	CREATED_BY                = "created_by"
	UPDATED_BY                = "updated_by"
	RESOURCE_TYPE_ID          = "resource_type_id"
	PARENT_RESOURCE_ID        = "parent_resource_id"
	PERMIT_ROLE_ASSIGNMENTS   = "role_assignments"
	POST                      = "POST"
	GET                       = "GET"
	DELETE                    = "DELETE"
	PATCH                     = "PATCH"
	CORG_RESOURCE_TYPE_ID     = "ed113dd2-bbda-11ef-87ea-c03c5946f955"
	TENANT_RESOURCE_TYPE_ID   = "ed113bda-bbda-11ef-87ea-c03c5946f955"
	CORG_ACCOUNT_OWNER_ID     = "account_owner_id"
	CORG_RELATION_TYPE        = "relation_type"
	CORG_STATUS               = "status"
	CORG_TAGS                 = "tags"
	TYPE                      = "type"
)
